---

apiVersion: v1
kind: ConfigMap
metadata:
  name: inway-service-config
  namespace: zgw
data:
  service-config.toml: |
    [services]
    # This block defines an API exposed by this inway.
    # A single inway can expose multiple API's, therefore this block can be added multiple times.
    # The name of the API must be unique for each block.
      [services.ac]
      endpoint-url = "https://autorisaties-api.vng.cloud/api/v1/"
      documentation-url = "https://autorisaties-api.vng.cloud/"
      authorization-model = "none"
      api-specification-document-url = "https://autorisaties-api.vng.cloud/api/v1/schema/openapi.yaml"
      # public-support-contact = "support@my-organization.nl"
      # tech-support-contact   = "tech@my-organization.nl"

      # [services.brc]
      # endpoint-url = "https://besluiten-api.vng.cloud/api/v1/"
      # documentation-url = "https://besluiten-api.vng.cloud/"
      # authorization-model = "none"
      # api-specification-document-url = "https://besluiten-api.vng.cloud/api/v1/schema/openapi.yaml"

      # [services.drc]
      # endpoint-url = "https://documenten-api.vng.cloud/api/v1/"
      # documentation-url = "https://documenten-api.vng.cloud/"
      # authorization-model = "none"
      # api-specification-document-url = "https://documenten-api.vng.cloud/api/v1/schema/openapi.yaml"

      # [services.nrc]
      # endpoint-url = "https://notificaties-api.vng.cloud/api/v1/"
      # documentation-url = "https://notificaties-api.vng.cloud/"
      # authorization-model = "none"
      # api-specification-document-url = "https://notificaties-api.vng.cloud/api/v1/schema/openapi.yaml"

      # [services.zrc]
      # endpoint-url = "https://zaken-api.vng.cloud/api/v1/"
      # documentation-url = "https://zaken-api.vng.cloud/"
      # authorization-model = "none"
      # api-specification-document-url = "https://zaken-api.vng.cloud/api/v1/schema/openapi.yaml"

      # [services.ztc]
      # endpoint-url = "https://catalogi-api.vng.cloud/api/v1/"
      # documentation-url = "https://catalogi-api.vng.cloud"
      # authorization-model = "none"
      # api-specification-document-url = "https://catalogi-api.vng.cloud/api/v1/schema/openapi.yaml"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: inway-service-certs
  namespace: zgw
data:
  root.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFjjCCA3agAwIBAgIUETfEQ3CBxDQoa7TxaXlDzNHOFbowDQYJKoZIhvcNAQEN
    BQAwXzELMAkGA1UEBhMCTkwxFjAUBgNVBAgTDU5vb3JkLUhvbGxhbmQxEjAQBgNV
    BAcTCUFtc3RlcmRhbTEWMBQGA1UEChMNQ29tbW9uIEdyb3VuZDEMMAoGA1UECxMD
    TkxYMB4XDTE4MDIyMzExMTkwMFoXDTIzMDIyMjExMTkwMFowXzELMAkGA1UEBhMC
    TkwxFjAUBgNVBAgTDU5vb3JkLUhvbGxhbmQxEjAQBgNVBAcTCUFtc3RlcmRhbTEW
    MBQGA1UEChMNQ29tbW9uIEdyb3VuZDEMMAoGA1UECxMDTkxYMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEA1hyosh5cOJZTvclIayyjTXqQQmLwTXKy4Ub1
    4rRgctPUc9C4JsXRxg1TPTWSMY66f0WPWsrh+nRKrSvHh+dY7tdye9fKCbmM4CnT
    GQS9ckmHU9i8eUHzv53tjkfZuA5fiuoEcSHx9aaOu/8DVvhix0XGzK5LRUkz/iCY
    gNo1f/uXyel9B50je9La67xERfXtd8zN4vNryB/wQn4C6ERDW/npREM0Geapuo45
    FojXbtseEPiDe/6iQwPaS1rcQzJFTzStA31frxF8wPb30XuoCZimbm3gyQSuBn0u
    fSgclOH0tZUXeJIdPbs6fbTnWeAedItwIkAlnKF5UUrNg9hqVE6/tSPIvIHra1F0
    zrc/1UL9EMdp59vnO7viYIpzAs5sBEQU1wmxK+xU05iBj0LiMo5tX6eT6tem/n7q
    k8FIYt5Iy0kgMT6k7TmJ/H4dualEELffk/+ATXonSX8auipS1aUBUM2tpfn/kxFM
    m4CvCv5Gt2/3/M2DFH/EN+hCHldQYMbBoHlCFh3Co6s4rJf5Im0lSIu2R1dS5k5I
    Yq4m5qhzlUgoQptAywhp6PVhSLPb1iL0cU8wSHlA2v3Pr5zVgH5HNt0xcyh/mECY
    BIeNMnuIoHkg62t218YyTwioXjjDVRnxtzPOoGm52Zb9v0cmbzSf/mrcC2Gx9SOj
    9M3yzj8CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8w
    HQYDVR0OBBYEFFrgQVERh6zaaIfAAMMGXOJ5LYn9MA0GCSqGSIb3DQEBDQUAA4IC
    AQAER3nogPn9weENdFDM0WbXFmQEMdJc1rppKYqTYSj/SSLI6vGK6i/PgrSmGy6N
    9dgJnHPWvqffyfXISsZpUE0zWaMqrIHLvk+yxhhAFxYuLWIr7li8XE73dBfPS0An
    y76rTbYQJuglLtnCl3urOvuLubzEFKYkVp3esmQnx/2tiarnT7RZq4RUM+4qf4jg
    fJFJqxC7Yk1re88cOgW1VKuMkdKuFrHgd34qIn/haN3AuEcGwvMRXb1BrHuJuIsP
    +8fb8VwLHuAe8d0vVgn99Dh1lGzAMeDVzaZSYMZb/YnuZ2GYOzZAH9bA0LYdNYGg
    LpiGDkoJvWqPKZgC4C8ucy8H8meVp6koVRa1/Edm8rmEEvOE3xDZAGtHNg/NAedx
    RBp8u4ujHMdpBb2XO0R4djzIm0iRFa3AB0OwQP7/Oln3paJf5lh8EdEtCpGRxOGd
    XjA+LiNx9tWoi/wsE7xil02wwi7jgznJEf5U26WLhhmpP3/s24KOarJcXkUFvOgY
    AxBiKxa0IvQBkDWJb0OnP8SVpoltjKtNQOAGF7ngzHB0SkJlsAQspiTOBS1YeZ+4
    4rGOiVIygm2313ofR8kPSFVLEGyW73TkZdj9ZR8vQuGXjEqNVUd9GHWhft3142co
    vKZ0d7BYa5Tc7mjzUomFPYM8BQQQqClyABHXf0lMwRKn6Q==
    -----END CERTIFICATE-----
  org.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGEDCCA/igAwIBAgIUdYI+OlV1xdpFtJZEpouo2fquyWkwDQYJKoZIhvcNAQEN
    BQAwXzELMAkGA1UEBhMCTkwxFjAUBgNVBAgTDU5vb3JkLUhvbGxhbmQxEjAQBgNV
    BAcTCUFtc3RlcmRhbTEWMBQGA1UEChMNQ29tbW9uIEdyb3VuZDEMMAoGA1UECxMD
    TkxYMB4XDTE5MDcwMjEzMDgwMFoXDTIwMDcwMTEzMDgwMFowgaMxCzAJBgNVBAYT
    Ak5MMRYwFAYDVQQIEw1Ob29yZC1Ib2xsYW5kMRIwEAYDVQQHEwlBbXN0ZXJkYW0x
    GjAYBgNVBAoTEXZuZy1yZWFsaXNhdGllLWJ2MSAwHgYDVQQLExdaYWFrZ2VyaWNo
    dCB3ZXJrZW4gQVBJczEqMCgGA1UEAxMhemFha2dlcmljaHR3ZXJrZW4taW53YXku
    dm5nLmNsb3VkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoV2yuH+h
    01iZWkORft54fywrdiFjAJMT4D5DNMk9UJ26rqL4gr9gQ+fGd+qEEK5t8faYx6mk
    FaFphl6z+30ajf9htgE83FgXo/1qFMg/Pg9xQxbYr4unfzT55eSQukQ07hMstfOM
    Kw1NOwTXzlWMqX8g9eSC+BDUOOG8rnYCOcRi8k5Pp5yjLSMa4tSGv/zQVC/3PLTI
    N+051nkVkZID3NGaqCq73XnRoQlM8A2EXILw5c7cR+7TvHvS1YYUQddDwSxdopMD
    +OilJQJaDu20nlbBZ9INfG1X4ZvwLiX7wp8kZ5UPmg+Tn9Apnk3z+eawJzlgVDZp
    LfkvT7HPhryPYiRNkYHAFunqFRsf11zchEdENnzsDrf9w3Xf7YUcKgfWHDanFVqM
    jujDr5SRjMj+cc8OrMcIde91jtrnOL+bm/Cl5qa34dj/afzqXQKWcKfVMurxYG1t
    CwJFNs9I2xdUslnwFGyyzmAesKyeHbz2kjHrffFX0PUZqJeL9ziyb/0BzYmjJ5+8
    B4jOV8w52Xql+7KgRvbLQsbAICEPDH4nq30KLu3uELJlcd39OjnRTlkxJHYKxJhL
    PnHCVv0FD9jRV//8jjR8S5kwvktc2qGd40xPs2J9eON9nJQcBmRQJRCN3uelOvPF
    MOHAejisLkv1sRfc1TNnGb3uM3mq3qcv6yUCAwEAAaN/MH0wDgYDVR0PAQH/BAQD
    AgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA
    MB0GA1UdDgQWBBT7zuNKzISohVVBoT40u+68QjXqeDAfBgNVHSMEGDAWgBRa4EFR
    EYes2miHwADDBlzieS2J/TANBgkqhkiG9w0BAQ0FAAOCAgEAcB1YXfIqNj7mmzUN
    2si9AUUbKSaovK0VrsuUlnJWD3yFulBkXR9uA9J/yx9f09H3ST2tgjFt8cYiJ8Wl
    +2sq/rorNoJGP18r4xo4bYD7pfdsu57UbvmhUVrEYqpB9Wn6nfGWS7xMz6zUkksg
    o6RqvIjA1/MlYPVrk62dPxTRx567oxgCBy+5e34Wofr3iVBkXFtrcTI91zXCjWed
    oSY5DWHMhdKp5kvfthcMcBiP33sos2pBdBT9IQq3tpARchlFR30iABcAqQjipDiC
    jbG1gca3CIR3Kdp36bHxHx3mbQ+d20+jgyQA7GoJHW13ZB+KxkN5tQKBC5Zg88RR
    m5mo1TCqGiF3WdeFNy+RAg0Vh24ORdfjFa61ClKyEUKupy8lttNhz+FDkEAlHwyt
    ufW0xa7Jk4bQrekx3V5m20fkJnrtf6V8/hWwB+dHzeRrDHwwvaaMd4OH4PE1RsCx
    xPtDQ9MNVtMGm48oAyDIXNhI7Npt0KB+eoFSaQJZFKhavdNjBIZVLeUrFhRx0dDx
    Gb7C/RM93uxJJL3bD17P+P1xlZ1jnKK5kKCVkKfzKCA5e87NTJn5QXUHa48XiJXs
    tFfVmJIndAqpoX7Gm92ZZ99Go/Q2bJrIUOlMGEIT52G+HMq+KJR3rVJ0/1TDwwCE
    c5WzdqtHMbaaAu1bnCN9yJ3DxPM=
    -----END CERTIFICATE-----

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nlx-inway
  namespace: zgw
  labels:
    k8s-app: nlx-inway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: nlx-inway
      labels:
        k8s-app: nlx-inway
    spec:
      volumes:
        - name: certs
          configMap:
            name: inway-service-certs
        - name: inway-service-config
          configMap:
            name: inway-service-config
        - name: keys
          secret:
            secretName: inway-secrets
      containers:
        - name: inway
          image: nlxio/inway:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "120Mi"
              cpu: "5m"
            limits:
              memory: "350Mi"
              cpu: "250m"
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8443
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8443
          env:
            - name: LOG_TYPE
              value: local
            - name: LOG_LEVEL
              value: debug
            - name: TLS_NLX_ROOT_CERT
              value: /certs/root.crt
            - name: TLS_ORG_CERT
              value: /certs/org.crt
            - name: TLS_ORG_KEY
              value: /keys/org.key
            - name: DISABLE_LOGDB
              value: "true"
            - name: SELF_ADDRESS
              value: zaakgerichtwerken-inway.vng.cloud:443
            - name: DIRECTORY_REGISTRATION_ADDRESS
              value: directory-registration-api.demo.nlx.io:443
            - name: SERVICE_CONFIG
              value: /inway-service-config/service-config.toml
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: inway-service-config
              mountPath: /inway-service-config
            - name: keys
              mountPath: /keys
      restartPolicy: Always

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: nlx-inway
  namespace: zgw
  labels:
    k8s-app: nlx-inway
spec:
  selector:
    k8s-app: nlx-inway
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
