# Inspired by https://docs.docker.com/compose/django/

# This is for development purposes ONLY. Do NOT run this in production with
# the same SECRET_KEYs.

version: '3.4'

services:
  # databases
  zrc_db:
    image: mdillon/postgis:10
    volumes:
      - zrc_postgres_data:/var/lib/postgresql/data

  drc_db:
    image: postgres:10
    volumes:
      - drc_postgres_data:/var/lib/postgresql/data

  ztc_db:
    image: postgres:10
    volumes:
      - ztc_postgres_data:/var/lib/postgresql/data

  brc_db:
    image: postgres:10
    volumes:
      - brc_postgres_data:/var/lib/postgresql/data

  # web
  zrc_web:
    image: vngr/gemma-zrc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=zrc.conf.docker
      - SECRET_KEY=c1zqz%y-s-$$63ca_abc8dmfjno#&pk!wy8k9f8c*4w@(whxy1n'
      - DB_HOST=zrc_db
    depends_on:
      - zrc_db
    ports:
      - "8000:8000"

  drc_web:
    image: vngr/gemma-drc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=drc.conf.docker
      - SECRET_KEY=h1kluf9r2yhcfr_i!fqb!srx=!u@!^b_gdl54=h0n15j34*+#=
      - DB_HOST=drc_db
    volumes:
      - drc_media:/app/media
    ports:
      - "8001:8000"
    depends_on:
      - drc_db

  ztc_web:
    image: vngr/gemma-ztc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=ztc.conf.docker
      - SECRET_KEY=)lwxn07vp1+ru=yf^n+v4l&ij24l3vhhitw9vk4=0ix14ibmfj
      - DB_HOST=ztc_db
    depends_on:
      - ztc_db
    ports:
      - "8002:8000"

  brc_web:
    image: vngr/gemma-brc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=brc.conf.docker
      - SECRET_KEY=u=y-#vjs0lw^%d13s8i=7r-880=-%5v!vmyzdoo=2go%ana4rc
      - DB_HOST=brc_db
    depends_on:
      - brc_db
    ports:
      - "8003:8000"

volumes:
  zrc_postgres_data:
  drc_postgres_data:
  drc_media:
  ztc_postgres_data:
  brc_postgres_data:
