---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ref-implementatie
  namespace: zgw
  labels:
    app.kubernetes.io/instance: zgw-test
    app.kubernetes.io/name: zgw
spec:
  rules:
  - host: zaakgerichtwerken.vng.cloud
    http:
      paths:
        - path: /
          backend:
            serviceName: docs
            servicePort: 80
  - host: zaken-api.vng.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: zrc
          servicePort: 8000
  - host: documenten-api.vng.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: drc
          servicePort: 8000
  - host: catalogi-api.vng.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: ztc
          servicePort: 8000
  - host: autorisaties-api.vng.cloud
    http:
      paths:
        - path: /
          backend:
            serviceName: ac
            servicePort: 8000
  - host: besluiten-api.vng.cloud
    http:
      paths:
        - path: /
          backend:
            serviceName: brc
            servicePort: 8000
  - host: notificaties-api.vng.cloud
    http:
      paths:
        - path: /
          backend:
            serviceName: nrc
            servicePort: 8000
  tls:
    - hosts:
        - zaakgerichtwerken.vng.cloud
        - zaken-api.vng.cloud
        - documenten-api.vng.cloud
        - catalogi-api.vng.cloud
        - autorisaties-api.vng.cloud
        - besluiten-api.vng.cloud
        - notificaties-api.vng.cloud
