---

# Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ service.name }}-celery
  namespace: zgw
  labels:
    k8s-app: {{ service.name }}-celery
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: {{ service.name }}-celery
  template:
    metadata:
      name: {{ service.name }}-celery
      labels:
        k8s-app: {{ service.name }}-celery
    spec:
      containers:
      - name: {{ service.name }}-celery
        image: vngr/notificaties-api:{{ service.image_tag }}
        imagePullPolicy: Always
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: nrc.conf.docker
          - name: DB_HOST
            value: {{ db_host }}
          - name: DB_NAME
            value: {{ service.name }}
          - name: RABBITMQ_HOST
            value: rabbitmq-{{ service.name }}
          - name: CELERY_LOGLEVEL
            value: WARNING
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: SECRET_KEY
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: DB_PASSWORD
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: SENTRY_DSN
          - name: PUBLISH_BROKER_URL
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: PUBLISH_BROKER_URL
          - name: CELERY_BROKER_URL
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: CELERY_BROKER_URL
          - name: CELERY_RESULT_BACKEND
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: CELERY_RESULT_BACKEND
        command: ["/celery_worker.sh"]
