---

# Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ service.name }}
  namespace: zgw
  labels:
    k8s-app: {{ service.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: {{ service.name }}
  template:
    metadata:
      name: {{ service.name }}
      labels:
        k8s-app: {{ service.name }}
    spec:
      containers:
      - name: {{ service.name }}
        image: vngr/notificaties-api:{{ service.image_tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "150Mi"
            cpu: "5m"
          limits:
            memory: "350Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: nrc.conf.docker
          - name: DB_HOST
            value: {{ db_host }}
          - name: DB_NAME
            value: {{ service.name }}
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: SECRET_KEY
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: DB_PASSWORD
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: SENTRY_DSN
          - name: PUBLISH_BROKER_URL
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: PUBLISH_BROKER_URL
          - name: CELERY_BROKER_URL
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: CELERY_BROKER_URL
          - name: CELERY_RESULT_BACKEND
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: CELERY_RESULT_BACKEND

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: {{ service.name }}
  namespace: zgw
  labels:
    k8s-app: {{ service.name }}
spec:
  selector:
    k8s-app: {{ service.name }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
