---

# Runtime secrets. Values are base64 encoded

kind: Secret
apiVersion: v1
metadata:
  name: {{ service.name }}-secrets
  namespace: zgw
type: Opaque
data:
  SECRET_KEY: {{ secret_keys.ac | b64encode }}
  DB_PASSWORD: {{ db_password | b64encode }}
  SENTRY_DSN: {% if sentry_dsns.ac %}{{ sentry_dsns.ac | b64encode }}{% else %}''{% endif %}
