title = "GEMMA Zaken API Guide"
theme = "nlx"
languageCode = "nl-nl"
baseURL = "https://ref.tst.vng.cloud/"
DefaultContentLanguage = "nl"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.docs]]
  name = "Introductie"
  weight = 10
  identifier = "introduction"
  url = "/"

[[menu.docs]]
  name = "Ontwikkelaars"
  weight = 20
  identifier = "developers"
  url = "/developers/"

[[menu.docs]]
  name = "Architectuur"
  weight = 30
  identifier = "architectuur"
  url = "/architectuur/"

[[menu.docs]]
  name = "Community"
  weight = 40
  identifier = "community"
  url = "/community/"

[[menu.docs]]
  name = "Functioneel"
  weight = 50
  identifier = "functioneel"
  url = "/functioneel/"
