title = "GEMMA Zaken API Guide"
theme = "nlx"
languageCode = "nl-nl"
baseURL = "https://ref.tst.vng.cloud/"
DefaultContentLanguage = "nl"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.docs]]
  name = "Introductie"
  weight = 1
  identifier = "introduction"
  url = "/"

[[menu.docs]]
  name = "Ontwikkelaars"
  weight = 2
  identifier = "developers"
  url = "/developers/"



[[menu.docs]]
  name = "Community"
  weight = 40
  identifier = "community"
  url = "/community/"
